// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABH3futz2KnMmQ-xJCY3hK560pndso4Qg',
    appId: '1:905052384832:web:800c16eda50926745bb9a5',
    messagingSenderId: '905052384832',
    projectId: 'creature-care-29be6',
    authDomain: 'creature-care-29be6.firebaseapp.com',
    storageBucket: 'creature-care-29be6.firebasestorage.app',
    measurementId: 'G-LVRXQ28Z0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS18ukSgJTWfrwolz8X68RHgxjdRJdke8',
    appId: '1:905052384832:android:0fc1ab031f660b0a5bb9a5',
    messagingSenderId: '905052384832',
    projectId: 'creature-care-29be6',
    storageBucket: 'creature-care-29be6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7oA8Kx5oLw8Zn4Xy_R8lFO7M4LKUBUqM',
    appId: '1:905052384832:ios:bc400072d310fd575bb9a5',
    messagingSenderId: '905052384832',
    projectId: 'creature-care-29be6',
    storageBucket: 'creature-care-29be6.firebasestorage.app',
    iosBundleId: 'com.example.creatureCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7oA8Kx5oLw8Zn4Xy_R8lFO7M4LKUBUqM',
    appId: '1:905052384832:ios:bc400072d310fd575bb9a5',
    messagingSenderId: '905052384832',
    projectId: 'creature-care-29be6',
    storageBucket: 'creature-care-29be6.firebasestorage.app',
    iosBundleId: 'com.example.creatureCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABH3futz2KnMmQ-xJCY3hK560pndso4Qg',
    appId: '1:905052384832:web:694eea67c3a793315bb9a5',
    messagingSenderId: '905052384832',
    projectId: 'creature-care-29be6',
    authDomain: 'creature-care-29be6.firebaseapp.com',
    storageBucket: 'creature-care-29be6.firebasestorage.app',
    measurementId: 'G-29SQPWNLJG',
  );
}
